### ISSUE TITLE
Cannot perform any queries in Flows tab "something went wrong" followed by csv headers

### ISSUE THREAD

**Issue by falz** [mbolli/nfsen-ng#116]
Recent install, building a new server with nfsen-ng instead of nfsen.

All flows are collecting properly, graphs / rrd's updating. When I issue any query, i get 

```
 something went wrong. firstSeen,duration,proto,srcAddr,srcPort,dstAddr,dstPort,packets,bytes,flows
```

and in some queries i get that as well as this, which is what looks like because $output is empty (the above issue? unsure)

```
Warning: Undefined array key 0 in /opt/nfsen-ng/nfsen-ng-0.3.1/backend/processor/Nfdump.php on line 175
```

I was running the HEAD/master version, and then switched to the last release 0.3.1 and get the same issue. I've turned on debugging which gives the nfdump command in the apache web logs - i can run it no probem as the www-data (apache) user, so permissions are ok. the values after "something went wrong" re the .csv headers - they change depending on the query, but i never see results.

Guessing this is something wrong compatibility wise - my system is I followed the INSTALL.md instructions (which were pretty great)

* Ubuntu 20.4.x
* PHP 8.1
* nfdump 1.7.5 (which, btw, is only two weeks old)

![image](https://github.com/user-attachments/assets/74bf3a82-8c29-40b5-bd2e-c13aecb3ddf8)

**Comment by falz** [comment]
Did a little more investigation here - i believe there are many issues, and perhaps the main one is the way nfsen 1.7.x outputs data. 

Eyeballing `processor/Nfdump.php` does a lot of things with the output such as "remove the 3 summary lines at the end of the csv output" - these three lines aren't there in 1.7.5, but are in 1.6.x. haven't tested any other versions, will do more looking around next week but it seems to simply not like the output.

Strangely though, the "if last element contains a colon, it's not a csv" portion of code doesn't even work - it seems that that returns a non csv as a bunch of text, but still errors.

if I choose to download a csv file i get a nice error:
```
<br />
<b>Fatal error</b>:  Uncaught TypeError: fputcsv(): Argument #2 ($fields) must be of type array, string given in /opt/nfsen-ng/gitmaster/backend/api/Api.php:103
Stack trace:
#0 /opt/nfsen-ng/gitmaster/backend/api/Api.php(103): fputcsv()
#1 /opt/nfsen-ng/gitmaster/backend/index.php(12): mbolli\nfsen_ng\api\Api-&gt;__construct()
#2 {main}
  thrown in <b>/opt/nfsen-ng/gitmaster/backend/api/Api.php</b> on line <b>103</b><br />
```

**Comment by mbolli** [comment]
In recent nfdump versions there has been mentions of a json output. Maybe this would be better suited...

**Comment by falz** [comment]
I went from NFdump 1.7.5 -> 1.7.4 and things actually work now, so there's some incompatibility w/ 1.7.5. And indeed it says json output is supported since 1.6.17.

However, I also get "Unknown Extension ##" in the nfsen command output. This also comes through if i run the command from CLI as well.  Guessing this is an Nfcapd/Nfdump issue, but perhaps they could be filtered out on the Nfsen-ng side?


![image](https://github.com/user-attachments/assets/8ec246e5-e0a6-4e84-a82d-fe38ee24a7b0)

**Comment by falz** [comment]
Additional note - the graphs for "ports" wasnt working either - and now it is.

**Comment by phaag** [comment]
> I went from NFdump 1.7.5 -> 1.7.4 and things actually work now, so there's some incompatibility w/ 1.7.5. And indeed it says json output is supported since 1.6.17.
> 
> However, I also get "Unknown Extension ##" in the nfsen command output. This also comes through if i run the command from CLI as well. Guessing this is an Nfcapd/Nfdump issue, but perhaps they could be filtered out on the Nfsen-ng side?
> 
> ![image](https://private-user-images.githubusercontent.com/707319/384638077-8ec246e5-e0a6-4e84-a82d-fe38ee24a7b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyMjk4NzgsIm5iZiI6MTczMTIyOTU3OCwicGF0aCI6Ii83MDczMTkvMzg0NjM4MDc3LThlYzI0NmU1LWUwYTYtNGU4NC1hODJkLWZlMzhlZTI0YTdiMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMFQwOTA2MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZjRlMzFkNzkyN2MzYWIzOGQyZDE5MGExZDlhZGM1ZGFmMTQxZjg0OTA5ZjdhZTJmZTM4N2U0ZGIxMmE5MDQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.rFIMXSgvyIxJxeMdn-aGWU3M7aP9mh5IR4vUbFsIoFU)

You have incompatible version of the collector `nfcapd` and the cli tool `nfdump`. The collector is newer.

**Comment by falz** [comment]
Indeed as i had just downgraded. 1.7.4 -> 1.7.5

After waiting a day and doing a few tests on data since, downgrading, i am not getting this error.

So perhaps this ticket should be renamed to "nfsen-ng incompatible with nfdump 1.7.5 - want me to open a new issue for that and close this?

**Comment by mbolli** [comment]
No let's leave it in here, I renamed the issue. 
Also thanks @phaag for chiming in.

**Comment by d4nys3k** [comment]
These commits seems to be cause. CVS header in nfdump changed and broke nfsen-ng...
https://github.com/phaag/nfdump/commit/8b1416fc982ade185e79c7b8e2f92085432b38b0
https://github.com/phaag/nfdump/commit/23c7f4a64fb91e91e45ce9bc2c7245918cff269a

**Comment by falz** [comment]
^ Just confirming this is likely CSV (as in Comma Separated File)  header, not CVS (as in RCS). Was confused for a moment.

**Comment by d4nys3k** [comment]
> ^ Just confirming this is likely CSV (as in Comma Separated File) header, not CVS (as in RCS). Was confused for a moment.

sure, it's my typo :) CSV header (first line) in nfdump output was changed from `ts,td,sa,da,...` to new form `firstSeen,duration,srcAddr,dstAddr,...` (_shortened_) with `-o 'csv'` output format. Tested just by calling similar nfdump command over command-line and looking to headers in output of v1.7.1 compared to v1.7.6. Then I looked for commits in nfdump probably causing such problem... and I decided that nfsen-ng seems to have problem on it's frontend with new output, as old headers in CSV are expected here (output from nfdump is correctly sent in json from the backend, first line is issued command, second CSV header and rest are data).

**Comment by dgeo** [comment]
Tried to adapt here with no success at this time…
https://github.com/dgeo/nfsen-ng/tree/testfix-nfsen175

It seems the main problem resides in backend not parsing correctly data

**Comment by dgeo** [comment]
> In recent nfdump versions there has been mentions of a json output. Maybe this would be better suited...

This could simplify everything ! I just miss js-skills and time here :/

**Comment by mbolli** [comment]
The Docker image now builds nfdump 1.7.6. The CSV parsing in Nfdump.php has been rewritten with auto-detection of tab vs comma delimiters, safe array access (null coalescing), and explicit -o csv / -o json format flags. The 'Undefined array key 0' bug is fixed.
